In [47]:
import numpy as np 
import torch
from torch import nn

In [48]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [49]:
input_image = torch.rand(3, 28, 28) # B: 3
flat_1 = nn.Flatten()

print(callable(flat_1))

flat_image = flat_1(input_image)

print(input_image.shape)
print(flat_image.shape)

True
torch.Size([3, 28, 28])
torch.Size([3, 784])


In [50]:
linear_1 = nn.Linear(in_features = 784, out_features = 100)

print(callable(linear_1))

linear_1_images = linear_1(flat_image)

print(linear_1_images.shape)

True
torch.Size([3, 100])


In [51]:
relu_1 = nn.ReLU()

relu_images = relu_1(linear_1_images)

print(relu_images.shape)

torch.Size([3, 100])


In [52]:
input_image = torch.rand(3, 28, 28)

seq_layers = nn.Sequential(
    nn.Flatten(),
    nn.Linear(784, 20),
    nn.ReLU(),
    nn.Linear(20, 10)
)

logits = seq_layers(input_image)

print(logits.shape)

torch.Size([3, 10])


In [53]:
softmax = nn.Softmax(1)

preds = softmax(logits)

print(logits)
print('----------------------------------------------------------------------------------')
print(preds)

tensor([[-0.0598,  0.0465, -0.1384, -0.0745, -0.0882, -0.0192, -0.0992,  0.2838,
          0.1672,  0.1806],
        [-0.0130,  0.0386, -0.2201, -0.0941, -0.0697, -0.0400, -0.0171,  0.2213,
          0.1458,  0.3170],
        [-0.0284,  0.2068, -0.1185, -0.1626, -0.0330, -0.1156, -0.0915,  0.2312,
          0.2330,  0.3099]], grad_fn=<AddmmBackward0>)
----------------------------------------------------------------------------------
tensor([[0.0915, 0.1017, 0.0845, 0.0901, 0.0889, 0.0953, 0.0879, 0.1290, 0.1148,
         0.1163],
        [0.0950, 0.1000, 0.0772, 0.0876, 0.0897, 0.0924, 0.0946, 0.1200, 0.1113,
         0.1321],
        [0.0917, 0.1161, 0.0838, 0.0802, 0.0913, 0.0841, 0.0861, 0.1189, 0.1191,
         0.1287]], grad_fn=<SoftmaxBackward0>)


In [54]:
class NeuralNetwork(nn.Module):

    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


my_neural_network = NeuralNetwork().to(device)

print(my_neural_network)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [59]:
data = torch.rand(1, 28, 28, device = device)
logits = my_neural_network(data)
pred_probab = nn.Softmax(dim = 1)(logits)

print(pred_probab)

tensor([[0.0962, 0.0920, 0.1082, 0.0979, 0.0953, 0.1045, 0.1004, 0.1095, 0.1007,
         0.0953]], device='cuda:0', grad_fn=<SoftmaxBackward0>)


In [62]:
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='cuda:0')


In [67]:
for name, params in my_neural_network.named_parameters():
    print(f"layer name : {name}, layer weights: {params}")

layer name : linear_relu_stack.0.weight, layer weights: Parameter containing:
tensor([[ 0.0300, -0.0056,  0.0019,  ...,  0.0211,  0.0154, -0.0046],
        [ 0.0017,  0.0149, -0.0138,  ...,  0.0291,  0.0209, -0.0001],
        [ 0.0085, -0.0345,  0.0236,  ..., -0.0056,  0.0102, -0.0141],
        ...,
        [ 0.0004, -0.0343, -0.0208,  ...,  0.0011, -0.0023, -0.0242],
        [ 0.0104,  0.0184, -0.0196,  ...,  0.0116, -0.0153,  0.0198],
        [ 0.0205,  0.0317,  0.0054,  ..., -0.0347, -0.0087,  0.0284]],
       device='cuda:0', requires_grad=True)
layer name : linear_relu_stack.0.bias, layer weights: Parameter containing:
tensor([ 1.8047e-02,  2.8118e-02, -2.0948e-03,  1.8149e-02,  5.8673e-04,
         2.4200e-02,  3.3269e-02, -2.5000e-02, -3.2845e-02,  3.0154e-02,
         2.3236e-02,  3.1653e-02,  1.4369e-02,  1.0288e-02, -1.1270e-02,
        -2.7783e-02,  1.2961e-02, -7.8420e-03, -4.2082e-03, -9.1389e-03,
        -1.9182e-02, -1.3647e-02, -2.8708e-02,  8.0649e-04,  4.3747e-04,
   