In [12]:
import numpy as np
import cv2 as cv

In [13]:
img = cv.imread('E:\web-258273318.jpg' , cv.IMREAD_COLOR)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Mohammad\AppData\Local\Temp\ipykernel_8960\322870925.py:1: SyntaxWarning: invalid escape sequence '\w'
  img = cv.imread('E:\web-258273318.jpg' , cv.IMREAD_COLOR)


In [14]:
cv.line(img, (5,5), (200,150), (200,200,0),10)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [200, 200,   0],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]]

In [15]:
cv.rectangle(img, (5,5), (200,150), (255,0,255),8)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [200, 200,   0],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]]

In [16]:
cv.circle(img, (200,150), 50,(0,255,255), -1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [200, 200,   0],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]]

In [17]:
points =np.array([[30,50], [300,200],[100,70],[50,100]])
cv.polylines(img, [points], True, (255,0,0), 5)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [200, 200,   0],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]]

In [18]:
font = cv.FONT_HERSHEY_COMPLEX
cv.putText(img, 'Salam be hame', (20,20), font, 1, (255,0,0),3)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [200, 200,   0],
        [200, 200,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]],

       [[174, 119,  15],
        [174, 119,  15],
        [174, 119,  15],
        ...,
        [174, 119,  15],
        [174, 119,  15],
        [174, 119,  15]]

In [19]:
imgray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

In [20]:
img2 = imgray[100:300, 250:500]

In [21]:
imgray[100:300,250:500] = 20

In [22]:
b = img[:, :, 0]
g= img[:, :, 1]
r= img[:,:,2]

In [23]:
cv.imshow('City' , img)
cv.imshow('b' , b)
cv.imshow('g' , b)
cv.imshow('r' , r)
# cv.imshow('x', imgray)
# cv.imshow('y',img2)
# cv.imshow('e',imgray)
cv.waitKey(0)
cv.destroyAllWindows()