In [7]:
import numpy as np
import torch
from torchvision.transforms import ToTensor

In [8]:
arr1 = np.random.randint(1, 10, size = (4,2,3), dtype = np.uint8)  # (H, W, C) => (4, 2, 3)

In [12]:
transpose_arr = arr1.transpose((2, 0, 1))


tt = ToTensor()
tt_arr_1 = tt(arr1)
print(tt_arr_1.shape)
print(tt_arr_1)
print(transpose_arr/255)

torch.Size([3, 4, 2])
tensor([[[0.0353, 0.0314],
         [0.0314, 0.0353],
         [0.0314, 0.0275],
         [0.0275, 0.0196]],

        [[0.0078, 0.0235],
         [0.0039, 0.0353],
         [0.0157, 0.0353],
         [0.0353, 0.0275]],

        [[0.0314, 0.0353],
         [0.0039, 0.0314],
         [0.0078, 0.0353],
         [0.0118, 0.0275]]])
[[[0.03529412 0.03137255]
  [0.03137255 0.03529412]
  [0.03137255 0.02745098]
  [0.02745098 0.01960784]]

 [[0.00784314 0.02352941]
  [0.00392157 0.03529412]
  [0.01568627 0.03529412]
  [0.03529412 0.02745098]]

 [[0.03137255 0.03529412]
  [0.00392157 0.03137255]
  [0.00784314 0.03529412]
  [0.01176471 0.02745098]]]
